displayName=Log Basket
author=aidanmastro
description=Displays the number of logs in your log basket
tags=woodcutting,wc,axe,log,logs,basket,forestry,container,counter
plugins=com.logbasket.LogBasketPlugin
build=standard
